name: Build .NET

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  dotnet-build:
    uses: beardgame/.github/.github/workflows/dotnet-build.yml@main
