name: Publish .NET

on:
  push:
    tags:
      - v*

jobs:
  dotnet-publish:
    uses: beardgame/.github/.github/workflows/dotnet-publish.yml@main
    with:
      dotnet-version: |
        3.1.x
        6.0.x
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
