name: Publish .NET

on:
  push:
    tags:
      - v*

jobs:
  dotnet-publish:
    uses: beardgame/.github/.github/workflows/dotnet-publish.yml@main
    secrets:
      GITHUB_TOKEN: $GITHUB_TOKEN
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
